CREATE EXTENSION IF NOT EXISTS pgcrypto;
create domain ticketstatus as varchar(255)
    constraint ticketstatus_check check ((VALUE)::text = ANY
                                         ((ARRAY ['pending'::character varying, 'sold'::character varying])::text[]));

alter domain ticketstatus owner to postgres;

create domain email as varchar(255)
    constraint email_check check ((VALUE)::text ~~ '%_@_%.%_'::text);

alter domain email owner to postgres;

create domain lotterystatus as varchar(255)
    constraint lotterystatus_check check ((VALUE)::text = ANY
                                          ((ARRAY ['started'::character varying, 'ended'::character varying, 'created'::character varying])::text[]));

alter domain lotterystatus owner to postgres;


create sequence otp_id_seq;

alter sequence otp_id_seq owner to postgres;

alter sequence otp_id_seq owned by otp.id;

grant select, update, usage on sequence otp_id_seq to anon;

grant select, update, usage on sequence otp_id_seq to authenticated;

grant select, update, usage on sequence otp_id_seq to service_role;

create sequence user_ticket_id_seq;

alter sequence user_ticket_id_seq owner to postgres;

alter sequence user_ticket_id_seq owned by user_ticket.id;

grant select, update, usage on sequence user_ticket_id_seq to anon;

grant select, update, usage on sequence user_ticket_id_seq to authenticated;

grant select, update, usage on sequence user_ticket_id_seq to service_role;



create table "user"
(
    id         uuid                     default gen_random_uuid() not null
        primary key,
    created_at timestamp with time zone default now()             not null,
    name       text,
    email      email,
    password   text,
    role       text
);

alter table "user"
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on "user" to anon;

grant delete, insert, references, select, trigger, truncate, update on "user" to authenticated;

grant delete, insert, references, select, trigger, truncate, update on "user" to service_role;

create table lotterie
(
    id           uuid                     default gen_random_uuid() not null
        primary key,
    created_at   timestamp with time zone default now()             not null,
    name         text                                               not null,
    started_date date                                               not null,
    end_date     date                                               not null,
    admin        uuid                     default gen_random_uuid()
        references "user"
            on update cascade on delete cascade,
    status       lotterystatus                                      not null,
    cash_prize   double precision         default '0'::double precision,
    hour         time                     default '10:00:00'::time without time zone
);

alter table lotterie
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on lotterie to anon;

grant delete, insert, references, select, trigger, truncate, update on lotterie to authenticated;

grant delete, insert, references, select, trigger, truncate, update on lotterie to service_role;

create table ticket
(
    created_at timestamp with time zone default now()             not null,
    number     smallint                                           not null,
    lotterie   uuid                     default gen_random_uuid() not null
        references lotterie
            on update cascade on delete cascade,
    price      double precision                                   not null,
    status     ticketstatus             default 'pending'::character varying,
    id         uuid                     default gen_random_uuid() not null
        primary key,
    winner     boolean                  default false             not null
);

alter table ticket
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on ticket to anon;

grant delete, insert, references, select, trigger, truncate, update on ticket to authenticated;

grant delete, insert, references, select, trigger, truncate, update on ticket to service_role;

create table otp
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp with time zone default now() not null,
    "user"     uuid
        references "user",
    number     text
);

alter table otp
    owner to postgres;

grant select, update, usage on sequence otp_id_seq to anon;

grant select, update, usage on sequence otp_id_seq to authenticated;

grant select, update, usage on sequence otp_id_seq to service_role;

grant delete, insert, references, select, trigger, truncate, update on otp to anon;

grant delete, insert, references, select, trigger, truncate, update on otp to authenticated;

grant delete, insert, references, select, trigger, truncate, update on otp to service_role;

create table user_ticket
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp with time zone default now() not null,
    "user"     uuid
        references "user",
    ticket     uuid                     default gen_random_uuid()
        references ticket
);

alter table user_ticket
    owner to postgres;

grant select, update, usage on sequence user_ticket_id_seq to anon;

grant select, update, usage on sequence user_ticket_id_seq to authenticated;

grant select, update, usage on sequence user_ticket_id_seq to service_role;

grant delete, insert, references, select, trigger, truncate, update on user_ticket to anon;

grant delete, insert, references, select, trigger, truncate, update on user_ticket to authenticated;

grant delete, insert, references, select, trigger, truncate, update on user_ticket to service_role;

