CREATE EXTENSION IF NOT EXISTS pgcrypto;
create sequence otp_id_seq;

alter sequence otp_id_seq owner to postgres;

alter sequence otp_id_seq owned by otp.id;

grant select, update, usage on sequence otp_id_seq to anon;

grant select, update, usage on sequence otp_id_seq to authenticated;

grant select, update, usage on sequence otp_id_seq to service_role;

create sequence user_ticket_id_seq;

alter sequence user_ticket_id_seq owner to postgres;

alter sequence user_ticket_id_seq owned by user_ticket.id;

grant select, update, usage on sequence user_ticket_id_seq to anon;

grant select, update, usage on sequence user_ticket_id_seq to authenticated;

grant select, update, usage on sequence user_ticket_id_seq to service_role;

create domain ticketstatus as varchar(255)
    constraint ticketstatus_check check ((VALUE)::text = ANY
                                         ((ARRAY ['pending'::character varying, 'sold'::character varying])::text[]));

create domain email as varchar(255)
    constraint email_check check ((VALUE)::text ~~ '%_@_%.%_'::text);

create domain lotterystatus as varchar(255)
    constraint lotterystatus_check check ((VALUE)::text = ANY
                                          ((ARRAY ['started'::character varying, 'ended'::character varying, 'created'::character varying])::text[]));

create table if not exists "user"
(
    id         uuid                     default gen_random_uuid() not null
        primary key,
    created_at timestamp with time zone default now()             not null,
    name       text,
    email      email,
    password   text,
    role       text
);

create table if not exists lotterie
(
    id           uuid                     default gen_random_uuid() not null
        primary key,
    created_at   timestamp with time zone default now()             not null,
    name         text                                               not null,
    started_date date                                               not null,
    end_date     date                                               not null,
    admin        uuid                     default gen_random_uuid()
        references "user"
            on update cascade on delete cascade,
    status       lotterystatus                                      not null,
    cash_prize   double precision         default '0'::double precision,
    hour         time                     default '10:00:00'::time without time zone
);

create table if not exists ticket
(
    created_at timestamp with time zone default now()             not null,
    number     smallint                                           not null,
    lotterie   uuid                     default gen_random_uuid() not null
        references lotterie
            on update cascade on delete cascade,
    price      double precision                                   not null,
    status     ticketstatus             default 'pending'::character varying,
    id         uuid                     default gen_random_uuid() not null
        primary key,
    winner     boolean                  default false             not null
);

create table if not exists otp
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp with time zone default now() not null,
    "user"     uuid
        references "user",
    number     text
);

create table if not exists user_ticket
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp with time zone default now() not null,
    "user"     uuid
        references "user",
    ticket     uuid                     default gen_random_uuid()
        references ticket
);

create view lottery_view(id, name, status, cash_prize, nbre_ticker, total_sale) as
SELECT l.id,
       l.name,
       l.status,
       l.cash_prize,
       count(t.number) AS nbre_ticker,
       t2.total        AS total_sale
FROM lotterie l
         JOIN ticket t ON l.id = t.lotterie
         FULL JOIN (SELECT count(*) AS total,
                           t2_1.lotterie
                    FROM ticket t2_1
                    WHERE t2_1.status::text = 'sold'::text
                    GROUP BY t2_1.lotterie) t2 ON t2.lotterie = t.lotterie
GROUP BY l.cash_prize, l.status, l.name, t2.total, l.id;

