CREATE EXTENSION IF NOT EXISTS pgcrypto;
create domain ticketstatus as varchar(255)
    constraint ticketstatus_check check ((VALUE)::text = ANY
                                         ((ARRAY ['pending'::character varying, 'sold'::character varying])::text[]));

create domain email as varchar(255)
    constraint email_check check ((VALUE)::text ~~ '%_@_%.%_'::text);

create domain lotterystatus as varchar(255)
    constraint lotterystatus_check check ((VALUE)::text = ANY
                                          ((ARRAY ['started'::character varying, 'ended'::character varying, 'created'::character varying])::text[]));
create table if not exists "user"
(
    id         uuid                     default gen_random_uuid() not null,
    created_at timestamp with time zone default now()             not null,
    name       text,
    email      email,
    password   text,
    role       text
    );

alter table "user"
    owner to postgres;

create table if not exists lotterie
(
    id           uuid                     default gen_random_uuid() not null,
    created_at   timestamp with time zone default now()             not null,
    name         text                                               not null,
    started_date date                                               not null,
    end_date     date                                               not null,
    admin        uuid                     default gen_random_uuid(),
    status       lotterystatus                                      not null,
    cash_prize   double precision         default '0'::double precision,
    hour         time                     default '10:00:00'::time without time zone
    );

alter table lotterie
    owner to postgres;

create table if not exists ticket
(
    created_at timestamp with time zone default now()             not null,
    number     smallint                                           not null,
    lotterie   uuid                     default gen_random_uuid() not null,
    price      double precision                                   not null,
    status     ticketstatus             default 'pending'::character varying,
    id         uuid                     default gen_random_uuid() not null,
    winner     boolean                  default false             not null
    );

alter table ticket
    owner to postgres;

create table if not exists otp
(
    id         bigint generated by default as identity,
    created_at timestamp with time zone default now() not null,
    "user"     uuid,
    number     text
    );

alter table otp
    owner to postgres;

create table if not exists user_ticket
(
    id         bigint generated by default as identity,
    created_at timestamp with time zone default now() not null,
    "user"     uuid,
    ticket     uuid                     default gen_random_uuid()
    );

alter table user_ticket
    owner to postgres;

create table if not exists payment_request
(
    id         uuid default gen_random_uuid() not null,
    id_lottery uuid,
    id_user    uuid,
    name       text,
    account    text,
    banck      text
    );

alter table payment_request
    owner to postgres;

create table if not exists payment_proof
(
    id         uuid default gen_random_uuid() not null,
    link       text,
    id_lottery uuid,
    name       text default 'preuve de paiement'::text
    );

comment on column payment_proof.name is 'name';

alter table payment_proof
    owner to postgres;

