spring.application.name=guolo_api
spring.datasource.url=jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres?user=postgres.drxszumeyeyrxuxltdbg&password=Kj5VdlIEGs5hiqMk

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration