spring.application.name=guolo_api
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5500}/postgres?user=${DB_USER:postgres}&password=${DB_PASSWORD:postgres}
#spring.datasource.url=jdbc:postgresql://37.60.239.221:5500/postgres?user=postgres&password=postgres

spring.data.jdbc.dialect=postgresql
server.servlet.context-path=/api
spring.rabbitmq.host=${RABBIT_HOST:0.0.0.0}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.password=${RABBIT_PASSWORD:guest}
spring.rabbitmq.username=${RABBIT_USER:guest}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration