spring.application.name=guolo_api
spring.datasource.url=jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres?user=postgres.drxszumeyeyrxuxltdbg&password=Kj5VdlIEGs5hiqMk

server.servlet.context-path=/api

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration